version: '3.1'

volumes:
  geonetwork:
  esdata:
  pgdata:


networks:
  gn-network:
    driver: bridge


services:
  www:
    image: nginx
    ports:
      - 13080:80
    environment:
      # Only used for / redirect to default webapp
      - NGINX_PUBLIC_HOST=localhost
      #- NGINX_PUBLIC_HOST=www.indores.fr
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=13080
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - geonetwork
    networks:
      - gn-network


  database:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=mnhn
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=geonetwork
    volumes:
      - /appcont/bddinee/postgresql/data:/var/lib/postgresql/data
    restart: "no"
    ports:
      - "13432:5432"
    networks:
      - gn-network


  geonetwork:
    build:
      context: .
      dockerfile: Dockerfile
#    image: geonetwork:4.0.5
    restart: "no"
    ports:
      - 8080:8080
    environment:
      DATA_DIR: /catalogue-data

      JAVA_OPTS: >
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/catalogue-data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins

      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200

      KB_URL: http://kibana:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: database
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: geonetwork
      GEONETWORK_DB_USERNAME: mnhn
      GEONETWORK_DB_PASSWORD: changeme
    volumes:
      - /sites/bddiwork/www/data:/catalogue-data
    depends_on:
      - elasticsearch
      - database
    networks:
      - gn-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - gn-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /geonetwork/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
    networks:
      - gn-network
